version: '3.7'
services:
  surrealdb:
    container_name: surrealdb
    env_file:
      - ./server/config/.env
    entrypoint: 
      - /surreal 
      - start 
      - --user
      - $DB_USER
      - --pass
      - $DB_PASSWORD
    image: surrealdb/surrealdb:latest
    ports:
      - 8000:8000

  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - surrealdb

  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - surrealdb
